name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Zip frontend files
        run: zip -r build.zip ./*

      - name: Copy build to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: the-archive-app.com
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "build.zip"
          target: "/tmp/build.zip"

      - name: Run deploy script on server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: the-archive-app.com
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            bash ~/deploy/deploy_frontend.sh
